### ISSUE TITLE
AnonymousId not consistent across Cart/Checkout events

### ISSUE THREAD

**Issue by aduch** [rudderlabs/rudderstack-shopify-app#17]
I've been testing the new Shopify<>Rudderstack integration. One blocking issue I am having is that `anonymousId` only remains consistent when browsing home/category/product pages on the site. As soon as a user updates cart or starts checkout flow, a new `anonymousId` is assigned every event and you lose the ability to track a user all the way through checkout.

**Comment by arjunbanker** [comment]
Hi - I have been considering setting up Rudderstack and wondering if there are any updates on this issue? This seems like a pretty large/blocking issue.

**Comment by utsabc** [comment]
Hi @arjunbanker @aduch thanks for posting this issue we are checking this internally, will share an update soon. :)

**Comment by utsabc** [comment]
Hello @aduch @arjunbanker we have pushed a fix for this issue via the following PR in our source transformation
https://github.com/rudderlabs/rudder-transformer/pull/1331
For now closing this issue, please feel free to share any further feedback so that we can continue on improving the connector

**Comment by arjunbanker** [comment]
Hi there, has this fix been pushed to the active Shopify application? Because in our logging we are still noticing that Server-initiated events do not have matching sessionIDs to client session IDs - this blocks the ability to do things like run a/b tests that measure impact on client and server- generated events.
